@unless (post_password_required())
  <div id="comments" class="rounded-lg border border-line bg-surface p-9 max-md:p-5.5">
    @if (have_comments())
      <h2 class="mb-2 text-[clamp(24px,2.6vw,30px)]">{{ get_comments_number_text('Comments (0)', 'Comments (1)', 'Comments (%)') }}</h2>

      {{-- aws-comment-list: nested reply lists (generated by WordPress) are styled in content.css --}}
      <ol class="aws-comment-list mb-6">
        {!! wp_list_comments(['callback' => 'App\\render_comment', 'style' => 'ol', 'avatar_size' => 0, 'echo' => false]) !!}
      </ol>

      {!! get_the_comments_pagination(['prev_text' => '&larr;', 'next_text' => '&rarr;']) !!}
    @else
      <div class="mb-[26px]">
        <h2 class="mb-2 text-[clamp(24px,2.6vw,30px)]">{{ __('Join the discussion', 'sage') }}</h2>
        <p class="text-[15.5px] text-muted">{{ __('Questions, pushback or your own experience. I read and reply to every comment.', 'sage') }}</p>
      </div>
    @endif

    @if (comments_open())
      @php(comment_form([
        'class_form' => 'aws-commentform',
        'title_reply' => '',
        'title_reply_before' => '',
        'title_reply_after' => '',
        'comment_field' => '<textarea id="comment" name="comment" placeholder="Add to the discussion…" required></textarea>',
        'label_submit' => 'Post comment',
        'class_submit' => 'submit',
        'comment_notes_before' => '',
        'comment_notes_after' => '',
      ]))
    @elseif (get_comments_number())
      <p class="font-mono text-[12px]/[normal] font-medium text-[#88877f]">{{ __('Comments are closed.', 'sage') }}</p>
    @endif
  </div>
@endunless
